version: '3'
services:
  mysql:
    image: mysql:5.7.24
    networks:
      - frontend
    environment: 
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_DATABASE: agiler
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    
  frontend:
    ports:
      - 8080:8080
    networks:
      - frontend
    build:
      context: ./
      dockerfile: Dockerfile
  onboarding:
    ports:
      - 4000:4000
    
    networks:
      - frontend
    build:
      context: ../agiler-backend-onboarding
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_DATABASE: agiler

  mongo:
    image: mongo:latest
    networks:
      - frontend
  
networks:
  frontend:
    driver: bridge