version: '3'
services:
  frontend:
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
  onboarding:
    ports:
      - 4000:4000
    build:
      context: ../agiler-backend-onboarding
      dockerfile: Dockerfile
      environment:
        - NODE_ENV: ${NODE_ENV} 

  mongo:
    image: mongo:latest
  mysql:
    image: mysql:latest
    environment: 
      -MYSQL_ROOT_PASSWORD: root